from .libraries import list_items, list_libraries

CAPABILITIES = {
    "project": ["create", "inspect", "state_digest", "version", "undo", "redo", "diff", "checkpoint", "restore_checkpoint", "atomic_batch", "dry_run", "optimistic_concurrency", "video_mode_1080p30", "video_mode_1080p60", "video_mode_4k30", "video_mode_4k60"],
    "assets": ["image", "video", "audio", "subtitle", "font", "semantic_tags", "sha256_integrity", "deterministic_visual_saliency"],
    "scene": ["add", "delete", "move", "set_asset", "set_duration", "source_in", "playback_rate", "restore_scene", "scene_history", "rebuild_plan"],
    "layers": ["text", "rect", "image", "keyframes", "motion_presets", "shared_id", "shared_element_plan", "rendered_shared_morph"],
    "composition": ["cover", "contain", "native_window", "ambient", "auto_plan", "visual_analysis", "focus_aware_crop", "focus_tracking", "subject_crop_risk", "bulk_auto_compose", "focus_tags", "caption_zone_suggestion", "instant_crop_zoom"],
    "cinematic_grammar": ["dynamic_aspect_ratio", "scope_lock", "scope_reveal", "impact_pulse", "impact_cluster", "detail_burst", "memory_shards", "duration_preserving_fragmentation", "micro_cut_closeups"],
    "facts": ["set", "remove", "template_resolution"],
    "context": ["compact_context_pack", "scene_scoped_context", "cast_context", "recipe_examples"],
    "cast": ["character_registry", "display_name", "aliases", "focus_position", "subtitle_position", "speaker_color"],
    "performance": ["dialogue_scene_recipe", "speaker_tracking", "anime_band_direction", "beat_aligned_focus", "band_sequence_recipe", "reaction_shot_recipe", "low_cognition_scene_recipe"],
    "camera": ["static", "slow_push", "slow_pull", "pan_left", "pan_right", "pan_up", "pan_down"],
    "camera_easing": ["linear", "ease", "ease_in", "ease_out", "ease_in_out", "smooth"],
    "camera_anchor": ["center", "top", "bottom", "left", "right", "top_left", "top_right", "bottom_left", "bottom_right"],
    "camera_backend": ["subpixel_perspective_cubic", "adaptive_uhd_native_cubic"],
    "cinematic_frame_backend": ["moving_letterbox_bars"],
    "transitions": [x["id"] for x in list_items("transitions")],
    "transition_events": ["visual_plus_sfx", "timeline_derived_sfx_timing"],
    "environment": ["snow", "rain", "dust", "fog", "embers", "light_particles", "sparks", "fire", "smoke", "ash", "bokeh"],
    "filters": [x["id"] for x in list_items("filters")],
    "libraries": list_libraries(),
    "environment_direction": ["auto", "up", "down", "left", "right", "up_left", "up_right", "down_left", "down_right"],
    "environment_depth_hint": ["foreground", "midground", "background"],
    "audio": ["bgm", "ambience", "sfx", "dialogue", "volume", "fade_in", "fade_out", "loop", "mix", "limiter", "remove_track", "rhythm_analysis", "beat_grid", "onset_grid", "rhythm_cut_plan"],
    "captions": ["plain_text", "speaker", "speaker_color", "nine_zone_position", "font_size", "outline", "auto_wrap", "dialogue_styles", "bilingual_secondary_line", "srt_import", "automatic_asr", "update", "remove", "composition_aware_zone_suggestion"],
    "dialogue": ["scene_relative_text", "tts_asset_binding", "caption_binding", "fit_scene", "auto_visual_position", "automatic_reading_duration", "multi_line_sequence", "speaker_tracking", "emotion_hint", "bilingual_secondary_line", "update", "remove"],
    "render": ["scene", "scene_span", "preview_720p", "showcase_1080p", "final_1080p", "uhd_4k30", "uhd_4k60", "custom_resolution", "custom_fps", "mp4", "mov", "mkv", "webm", "h264", "hevc", "av1", "vp9", "prores", "nvenc_auto_fallback", "frame_extract", "contact_sheet", "render_manifest", "semantic_cache", "hierarchical_render_dag"],
    "enhancement": ["realesrgan_optional_install", "realesrgan_animevideov3_x2", "realesrgan_animevideov3_x4", "realesrgan_external_override", "rife_optional_ai_frame_interpolation", "anime_super_resolution_model", "hard_cut_interpolation_guard", "ai_runtime_failure_auto_fallback", "ffmpeg_lanczos_fallback", "ffmpeg_minterpolate_fallback", "third_party_backend_status", "explicit_backend_install"],
    "qa": ["missing_assets", "asset_hash_drift", "source_resolution", "source_duration", "invalid_duration", "transition_overlap", "aggressive_motion", "motion_continuity", "subtitle_length", "resolution", "duration", "audio_peak"],
    "cache": ["inspect", "clear_generated_cache"],
    "agent": ["machine_readable_state", "machine_readable_errors", "deterministic_effects", "semantic_operations", "state_conflict_detection", "read_only_snapshots", "operation_schema", "alias_normalization", "argument_normalization", "single_scene_inference", "transaction_preflight", "repair_suggestions", "safe_agent_gateway", "protocol_v4", "high_level_recipes", "warm_resume_capsule", "upgrade_resume_capsule", "task_scoped_context"],
    "subtitle_asr": ["whisper_cpp_optional", "ffmpeg_pcm_bridge", "language_auto_detect", "timestamped_json", "translate_to_english", "bilingual_alignment"],
    "gen3": ["jane3_alias", "stillness_first", "semantic_scene_kinds", "category_label", "two_line_info_card", "timed_blur_card", "magenta_matte_key", "despill", "actor_cards", "contact_shadow", "actor_motion", "tile_refinement_2x2", "overlap_feather_stitch", "remotion_bridge", "ffmpeg_fallback", "uhd_4k30_default", "uhd_4k60_optional"],
    "runtime": ["direct_checkout_runner", "discover", "doctor", "backend_auto", "one_command_quickstart", "agent_start_capsule", "warm_resume", "upgrade_resume", "minimal_token_bootstrap"],
}
